apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1    
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 387584877503.dkr.ecr.us-east-1.amazonaws.com/my-sql:v0.3
        name: sql-deployment
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        volumeMounts:
        - name: mysql-pvc
          mountPath: /data/db          
        ports:
        - containerPort: 3306
      volumes:
       - name: mysql-pvc
         persistentVolumeClaim:
           claimName: mysql-pvc         
